name: Deploy to Heroku

on:
  push:
    branches:
      - main

env:
  APP_NAME: ${{secrets.HEROKU_APP}}
  API_KEY: ${{secrets.HEROKU_API_KEY}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Heroku
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: dpl install
        run : gem install dpl

      - name: run dpl
        run: echo ${{secrets.HEROKU_APP}}

      - run: dpl --provider=heroku --api_key=$API_KEY --app=$APP_NAME
