name: Deploy to Heroku

on:
  push:
    branches:
      - master

env:
  APP_NAME: ${{ secrets.HEROKU_APP }}
  API_KEY: ${{ secrets.HEROKU_API_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: heroku-deploy
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: dpl install
        run : gem install dpl

      - name: run dpl
        run: dpl --provider=heroku --api-key=$APP_NAME --app=$API_KEY
