name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: Heroku
    steps:
      - uses: actions/checkout@v2
      - uses: extractions/netrc@v1
        with:
          machine: git.heroku.com
          username: ${{ secrets.HEROKU_EMAIL }}
          password: ${{ secrets.HPASSWORD }}
      - run: git remote set-url heroku https://git.heroku.com/famcs-game-server.git
      - run: git push heroku main
